### ISSUE TITLE
How to handle CORS errors when using linkedin-jobs-api?

### ISSUE THREAD

**Issue by bitcooker** [VishwaGauravIn/linkedin-jobs-api#1]
This is what occurs on the site. (https://future-planner.vercel.app/)

![image](https://user-images.githubusercontent.com/128102810/234157821-eb7c858b-35ae-4e16-a565-6f30819d10ea.png)

Why it happens? and what's the solution?

**Comment by Hamdysaad20** [comment]
did you solve it ?
@bitcooker

**Comment by VishwaGauravIn** [comment]
Hey @bitcooker , sorry I didn't get notification about this issue. 
by the way you can call it from server side, or use API if using NEXTJS
