### ISSUE TITLE
The company logo not working

### ISSUE THREAD

**Issue by humzasadiq** [VishwaGauravIn/linkedin-jobs-api#5]
there is a default image for every company logo 
![image](https://github.com/VishwaGauravIn/linkedin-jobs-api/assets/104767329/888a110f-bbf4-42b1-b0e8-0ba05860f91a)

**Comment by humzasadiq** [comment]
on inpecting the logo its attr is **src** not _data-delayed-url_ or _data-ghost-url_.

**Comment by humzasadiq** [comment]
can you tell when this can be fixed I need this for my Uni project:)

**Comment by VishwaGauravIn** [comment]
Which version of linkedin-jobs-api are you using?
